# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-feed

# Site settings
title: "Kaŭzoj"
description: >
   Causes to be active about.

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
paginate:	5
url: "https://kauzoj.github.io"
baseurl: ""
twitter_handle: '@kauzoj'
social:
  - icon:	twitter
    url:	https://twitter.com/kauzoj
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon:	github
    url:	https://github.com/kauzoj
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
contactpoints:
  - icon:	twitter
    url:	https://twitter.com/thetoxicarcade
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon:	github
    url:	https://github.com/kauzoj
    desc:	Contribute on GitHub
    share_url:
    share_title:
    share_link:
  - icon:	google
    url:	mailto:kauzojmedia@gmail.com
    desc:	Email Us
    share_url:
    share_title:
    share_link:
  - icon: telegram
    url:	https://telegram.me/kauzoj
    desc:	Chat with us on Telegram
    share_url:
    share_title:
    share_link:
  - icon: facebook
    url:	https://facebook.com/kauzoj
    desc:	Follow us on Facebook
    share_url:
    share_title:
    share_link:

exclude:
  - Gemfile
  - Gemfile.lock
  - secret.key
  - api/

radar:
  search:
    - people running for office
      - gaining representation
    - sites for causes
    - news outlets
    - opinionated youtube channels
quicktags:
  concept:
    style: concept
    msg: "This is a concept post"
  editing:
    style: editing
    msg: "This post is marked as undergoing editing"
  opinion:
    style: opinion
    msg: "This is an opinion based post. (most of our stuff is...)"
  review:
    style: review
    msg: "This post is ready for review"
  urgent:
    style: urgent
    msg: "Hey. Editing this is urgent"
  WIP:
    style: WIP
    msg: "This is a WIP"
pagelinks:
  about:
    title: about
    url: /about/
  causes:
    title: causes
    url: /causes/
external:
  github_link:
    url: https://github.com/kauzoj/kauzoj.github.io
    title: Kauzoj Source.
bios:
  Aelx:
    name: Cameron Whiting
    bio: >
      Well, much ado about something
    author_image: "/assets/images/author.jpg"
  all:
    name: Kaŭzoj Writers
    bio: >
      Kaŭzoj is written by a great team. Learn
      more [here]](/people/).
    author_image: "/assets/images/author.jpg"
columns:
  - 0:
    title: Affirmative Failure
    code: AF
  - 1:
    title: Structural Tango, Policy Freestyle
    code: STPF
  - 2:
    title: This Week's Fourier Transform
    code: TWFT
  - 3:
    title: The Ordinary Mishap
    code: TOM
  - 4:
    title: Private Divorce
    code: PD
  - 5:
    title: '*Internal Screaming* "[External Justification]"'
    code: ISEJ
  - 6:
    title: Recollect, Rebuttal, Rewind
    code: RRR
